name: links
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  
  # Firebase ..
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.5.3

  # ...
  font_awesome_flutter: ^10.4.0
  get_storage: ^2.0.3
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.1.0
  share_plus: ^7.2.1
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.0+1
  pull_down_button: ^0.9.3
  image_picker: ^1.0.0
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  fonts:
    - family: ar_font
      fonts:
        - asset: assets/fonts/ar/Montserrat-Arabic-Light.ttf

    - family: en_font
      fonts:
        - asset: assets/fonts/en/Co Headline Bold.otf
        - asset: assets/fonts/en/Co Headline Light.otf

  assets:
    - assets/images/

